// Generated by node-private-tools
// tslint:disable:max-line-length
// tslint:disable:whitespace
import { Pipe, PipeTransform } from '@angular/core';

export enum UserCashType { TUserCashUnknown,TUserCashPrepay,TUserCashPrepayBack,TUserCashTrade,TUserCashRefund,TUserCashPreWithdraw,TUserCashWithdraw,TUserCashReward,TUserCashRebate,TUserCashRecharge }
export enum TradeState { UNKNOWN,NOTPAY,SUCCESS,REFUND,CLOSED,REVOKED,USERPAYING,PAYERROR }
export enum OrderState { TOrderStateUnknown,TOrderStateNopay,TOrderStateCanceled,TOrderStatePrepaid,TOrderStatePaid,TOrderStateRejected,TOrderStateEnsuring,TOrderStateEnsured,TOrderStateRefund,TOrderStateCompleted,TOrderStateEvaled,TOrderStateHistory }

export const pretties = {
  UserCashType: ['未知','预付款','预付款退回','交易','退款','预提现','提现','奖励','返利','充值'],
  OrderState: ['未知状态','待付款','已关闭','支付中','已付款','已拒绝','等待确认','已确认','已退款','已完成','已评价','已评价'],
};

@Pipe({ name: 'UserCashType' })
export class UserCashTypePipe implements PipeTransform {
  transform(value: number) {
    return pretties.UserCashType[value] || '';
  }
}
@Pipe({ name: 'OrderState' })
export class OrderStatePipe implements PipeTransform {
  transform(value: number) {
    return pretties.OrderState[value] || '';
  }
}

export const GEN_CONST_PIPES = [
  UserCashTypePipe,
  OrderStatePipe,
];
