// Generated by node-private-tools
import { Pipe, PipeTransform } from '@angular/core';
export const trans = {
  SetUserInfoPayload: {
    Nickname: '昵称',
    Sex: '性别',
  },
};

@Pipe({ name: 'SetUserInfoPayload' })
export class SetUserInfoPayloadPipe implements PipeTransform {
  transform(value: string) {
    return (<any>trans).SetUserInfoPayload[value] || value;
  }
}

export const GEN_TRANS_PIPES = [
  SetUserInfoPayloadPipe,
];
